---
micronaut:
  application:
    name: configuration-service

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"


jackson:
  serialization:
    writeDatesAsTimestamps: false
  deserialization:
    writeDatesAsTimestamps: false

micronaut:
  server:
    cors:
      enabled: true

redis:
  uri: redis://localhost:6379